name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install flake8 pytest pytest-cov
#          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install poetry
        run: |
          pip install poetry

      - name: Install requirements
        run: |
          make install

      - name: Lint with flake8
        run: |
          make lint
#          # stop the build if there are Python syntax errors or undefined names
#          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          make pytest
      - name: coverage
        run: |
          make pytest-cov
#               >     pip install poetry
#                >    make install
#              >- uses: paambaati/codeclimate-action@v2.7.5
#               > env:
#               >   CC_TEST_REPORTER_ID: 268149fdc01b007176e8039f4ddfa1fa24d6596ddc2d759bde00b525a5f2c1d6
#               > with:
#                >  coverageCommand: make test-coverage
